# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently. Really should be used for sitewide changes.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brendan's Profile Page
email: brendan.davidson@colostate.edu
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my website! Pretty much anything you need to know about me can be found here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

  I am an assistant professor of sociology at Austin College in Sherman, TX. My research is at the crossroads of immigration policy and labor studies, with a specific focus on how and why U.S. immigration policy is changing from a family reunification and humanitarian-based model to one that increasingly privileges short-term immigration for labor purposes.  

I am also an activist and a member of Migration that Works, a coalition of labor, migration, civil rights, anti-trafficking organizations and academics advancing a labor migration model that respects the human rights of workers, families and communities and reflects their voices and experiences. Additionally, I am an affiliate member of the American Association of University Professors and love teaching about and being part of a union.

When I am not working I love being in nature or doing just about anything with my spouse, Scott, and our two boys, James and Theo.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://BrendanDavidson45.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  BrendanDavidson45

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

#header_pages:
#  - 01-about.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
